[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
savefile-abi = "0.17.0-beta.6"
savefile = "0.17.0-beta.6"
savefile-derive = "0.17.0-beta.6"
interface_crate = { path = "../interface_crate" }



