[package]
name = "implementation_crate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
savefile-abi = "0.17.0-beta.4"
savefile = "0.17.0-beta.4"
savefile-derive = "0.17.0-beta.4"
interface_crate = { path = "../interface_crate" }

